server:
  port: ${application.port}
  tomcat:
    max-threads: 500
    accept-count: 500
    min-spare-threads: 200

spring:
  application:
    name: ${application.name}
  profiles:
    include: main
  #    active: prd
  boot:
    admin:
      client:
        enabled: true
        auto-registration: true
        instance:
          prefer-ip: true
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 47.103.65.29
    port: 6379
    password: aR$5dG^k6P
    database: 0
    timeout: 500
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 8
        # 最大等待时间ms 默认-1无限等待
        max-wait: 100
        # 最大空闲连接数 默认8
        max-idle: 8
        # 最小空闲连接数 默认0
        min-idle: 0
    # 过期时间，单位为秒，默认0不设置过期时间
    ttl: 3600
    # 设置本项目所有缓存key的前缀，空时不设置前缀
    cache-prefix: "local-"
    # 设置key的前缀，默认为英文冒号:
    key-prefix: ":"
    # 添加记录是否同时添加到缓存，默认 true 添加缓存
    cache-insert: true
  datasource:
    one:
      type: com.alibaba.druid.pool.DruidDataSource
      jdbc-url: ${datasource.mysql.url}
      username: ${datasource.mysql.username}
      password: ${datasource.mysql.password}
      driver-class-name: com.mysql.cj.jdbc.Driver
      druid:
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 60000
        validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        filters: stat,wall
        filter:
          stat:
            log-slow-sql: true
            slow-sql-millis: 2000
      mybatis:
        mapper-locations: classpath*:mybatis/**/*.xml
  liquibase:
    enabled: false
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
  resources:
    static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

#热部署生效
#  devtools:
#    restart:
#      enabled: true

#mybatis:
#  type-aliases-package: com.forsrc.project.local.model
#  dao-locations: classpath*:mybatis/dao/*.xml

logging:
  level:
    root: ${log.level}
    com.project.local: ${log.level}
    com.project.local.repository: ${log.level}
    com.project.local.mapper: ${log.level}
  file: ${log.file}

thread:
  pool:
    corePoolSize: 10
    maxPoolSize: 50
    queueCapacity: 100
    keepAliveSeconds: 300

okhttp:
  connect-timeout: 30
  read-timeout: 30
  write-timeout: 30
  # 连接池中整体的空闲连接的最大数量
  max-idle-connections: 200
  # 连接空闲时间最多为 300 秒
  keep-alive-duration: 300

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

feign:
  hystrix:
    enabled: true

token:
  key: L5H^k6U4a&Cf3J!k
  valid-day: 15