application:
  port: 8081
  name: dpi

datasource:
  name: mysql
  mysql:
    url: jdbc:mysql://localhost:3306/mydb?serverTimezone=PRC&autoReconnect=true&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: ''
    password: ''
    driver: com.mysql.cj.jdbc.Driver
  gp:
    url: jdbc:pivotal:greenplum://localhost:3307;DatabaseName=mydb
    username: ''
    password: ''
    driver: com.pivotal.jdbc.GreenplumDriver

log:
  level:
    root: info
    dao: debug
  file: log/app.log

websocket:
  enable: true
  port: 8011
  # minute
  message-timeout: 30
  #second
  login-timeout: 30

jwt:
  secret: secret
  expiration: 7200000
  token: Authorization
