server:
  port: ${application.port}
  tomcat:
    accept-count: 500
    threads:
      max: 500
      min-spare: 200

spring:
  application:
    name: ${application.name}
  profiles:
    include: main
